name: backend-ci

on:
  pull_request:
    branches: [main]

jobs:
  style:
    name: Style
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Lint
        run: cd wanderlux-be && npm run lint
